---
title: "Fall"
output:
  pdf_document: default
  html_notebook: default
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(rio)
library(tidyr)
library(dplyr)
library(stringr)
library(tableone)
library(labelled)
```



```{r}


## Loading the csv file

options(data.dir = "C:/Users/annan/OneDrive/Documents/GitHub/Fall_TITCo")

data.dir <- getOption("data.dir")

if (is.null(data.dir))
    stop ("Please set the directory where the data is kept using options(data.dir = \"<path to data directory>\")")

#TITCO dataset
titco_fall <- data.table::fread(file.path(data.dir,"titco-I-full-dataset-v1.csv"))

## Filter all fall patients
fall <- subset(titco_fall, titco_fall$moi == "Fall")

## to find the sample size
dm <- nrow(fall)

## Find no and % of males and females
m <- fall$sex == "Male"
n.m <- sum(m)
p.m <- round(mean(m) * 100)
f <- fall$sex == "Female"
n.f <- sum(f)
p.f <- round(mean(f)*100)

## Summarize age
## Break age into groups
agebreaks <- c(17,25,45,65,98)
agelabels <- c("18-24","25-44","45-64","65+")

fall$age <- as.numeric(fall$age)

fall$agegrp <-cut(fall$age,
                breaks = agebreaks,
                right = FALSE,
                labels = agelabels)


#Age group range 20
agebreaks <- c(0,11,21,31,41,51,61,71,81,91,101)
agelabels <- c("0-10","11-20","21-30","31-40","41-50","51-60","61-70","71-80","81-90","91-100")

fall$age <- as.numeric(fall$age)

fall$tagegrp <-cut(fall$age,
                breaks = agebreaks,
                right = FALSE,
                labels = agelabels)

## Find percentage transferred
t <- fall$tran == "Yes"
n.t <- sum(t,na.rm=T)
p.t <- round(mean(t,na.rm=T)*100)
## Find mode of transport 
am <- fall$mot == "Ambulance"
n.am <- sum(am,na.rm=T)
p.am <- round(mean(am,na.rm=T)*100)
## Find percentage of Type of injury
ti <- fall$ti == "Blunt"
n.ti <- sum(ti,na.rm=T)
p.ti <- round(mean(ti,na.rm=T)*100)

## Create GCS group
gcsbreaks <- c(2,8,13,15)
gcslabels <- c( "3-8", "9-13", "14-15")
fall$gcsgrp <-cut(fall$gcs_t_1,
                breaks = gcsbreaks,
                right = FALSE,
                labels = gcslabels)


## Find number of surgery done
tos <- fall$tos 
surg1<- ifelse(tos == 0, 0,
              ifelse(tos == 999, 0, 1))
surgery1 <- fall["Surgery"] <- surg1 == 1 
# @DB, can you pls check the above code
#I am getting the followin error:
#Error in `[.data.table`(x, i, which = TRUE) : 
#  When i is a data.table (or character vector), the columns to join by must be specified using 'on=' argument (see ?data.table), by keying x (i.e. sorted, and, marked as sorted, see ?setkey), or by sharing column names between x and i (i.e., a natural join). Keyed joins might have further speed benefits on very large data due to x being sorted in RAM.

n.s <- sum(surgery1, na.rm = TRUE)
p.s <- round(mean(surgery1, na.rm = TRUE)*100)

## Find mortality
died <- fall$died == "Yes"
n.died <- sum(died, na.rm = TRUE)
p.died <- round(mean(died, na.rm = TRUE) * 100)
## Find discharged against medical advice
dama <- fall$dama == "Yes"
n.dama <- sum(dama,na.rm = T)
p.dama <- round(mean(dama,na.rm = T)*100)

#ISS parameter value
issbreaks <- c(1,9,16,25,109)
isslabels <- c("Mild","Moderate","Severe","Profound")
fall$isspv <-cut(fall$iss,
                breaks = issbreaks,
                right = FALSE,
                labels = isslabels)

#Characteristics of Injury

fall <- suppressWarnings(suppressMessages(unite(fall, allinj, contains("icd"), sep = ",", remove = FALSE)))

crush_inj <- str_c(c("s07","s07.0","s07.1","s07.8","s07.9","s17","s17.0","s17.8","s17.9","s28.0","s38.0","s38.1","t04.1","s47","s57","s57.0","s57.8","s57.9","s67","s67.0","s67.8","t04.2","s77.0","s77.1","s77.2","s87","s87.0","s87.8","s97","s97.0","s97.1","s97.8","t04.3","t04.8","t04.9","t14.7"),collapse = "|")

crush <- filter(fall, str_detect(allinj, crush_inj))
crush$inj_type <- "Crush Injury"
rest <- suppressWarnings(suppressMessages(fall %>% anti_join(crush)))

amp_inj <- str_c(c("s08","s08.1","s08.2","s08.3","s08.4","s08.5","s08.6","s08.7","s08.8","s08.9","s18","s28.1","s38.2","s38.3","t09.6","s48","s48.0","s48.1","s48.9","s58","s58.0","s58.1","s58,9","s68","s68.0","s68.1","s68.2","s68.3","s68.4","s68.8","s68.9","t05.0","t05.2","t11.6","s78.0","s78.1","s78.2","s78.3","s78.4","s78.5","s78.6","s78.7","s78.8","s78.9","s88","s88.0","s88.1","s88.9","s98","s98.0","s98.1","s98.2","s98.3","s98.4","s78.0","t05.3","t05.5","t13.6","t05.8","t05.9"),collapse = "|")

amputation <- filter(rest, str_detect(allinj, amp_inj))
amputation$inj_type <- "Amputation"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(amputation)))

bv_inj <- str_c(c("s09.0","s15.0","s51.2","s15.3","s15.4","s15.5","s15.6","s15.7","s15.8","s15.9","s15.1","s25","s25.0","s25.1","s25.2","s25.3","s25.4","s25.5","s25.7","s25.8","s25.9","s35.0","s35.1","s35.2","s35.3","s35.4","s35.5","s35.7","s35.8","s35.9","s45","s45.0","s45.1","s45.2","s45.3","s45.7","s45.8","s45.9","s55","s55.0","s55.1","s55.2","s55.7","s55.8","s55.9","s65","s65.0","s65.1","s65.2","s65.3","s65.4","s65.5","s65.7","s65.8","s65.9","t11.4","s75","s75.0","s75.1","s75.2","s75.7","s75.8","s75.9","s85","s85.0","s85.1","s85.2","s85.3","s85.4","s85.5","s85.7","s85.8","s85.9","s95","s95.0","s95.1","s95.2","s95.7","s95.8","s95.9","t13.4","t06.3","t14.5"),collapse = "|")

bv <- filter(fall, str_detect(allinj, bv_inj))
bv$inj_type <- "Blood Vessel"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(bv)))

internal_inj <- str_c(c("s06","s06.0","s06.1","s06.2","s06.3","s06.4","s06.5","s06.6","s06.7","s06.8","s06.9","t90.5","s14.0","s14.1","s24.0","s24.1","s34.0","s34.1","s34.3","t09.3","t91.3","s14.2","s26.0","s27.0","s27.1","s27.2","s27.3","s27.4","s27.5","s27.6","s27.8","s27.9","t91.4","s36","s36.0","s36.1","s36.2","s36.3","s36.4","s36.5","s36.6","s36.7","s36.8","s36.9","s37","s37.0","s37.1","s37.2","s37.3","s37.4","s37.5","s37.6","s37.7","s37.8","s37.9","s39.6","s39.7","t06.5","t91.5"),collapse = "|")

internal <- filter(fall, str_detect(allinj, internal_inj))
internal$inj_type <- "Internal Injury"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(internal)))

frac_inj <- str_c(c("s02","s02.0","s02.1","s02.3","s02.7","s02.9","t90.2","s02.2","s02.4","s02.5","s02.6","s12","s12.8","s12.9","s12.0","s12.1","s12.2","s12.3","s12.4","s12.5","s12.6","s12.7","s22","s22.0","s22.1","s32","s32.0","s32.1","s32.2","t08","t91.1","s22.2","s22.3","s22.4","s22.5","s22.6","s22.7","s22.8","s22.9","s32.3","s32.4","s32.5","s32.6","s32.7","s32.8","t02.1","t91.2","s42","s42.0","s42.1","s42.2","s42.3","s42.4","s42.7","s42.8","s42.9","s52","s52.0","s52.1","s52.2","s52.3","s52.4","s52.5","s52.6","s52.7","s52.8","s52.9","s62","s62.0","s62.1","s62.2","s62.3","s62.4","s62.5","s62.6","s62.7","s62.8","t02.2","t02.4","t10","t92.1","t92.2","s72","s72.0","s72.1","s72.2","s72.3","s72.4","s72.5","s72.6","s72.7","s72.8","s72.9","s82","s82.0","s82.1","s82.2","s82.3","s82.4","s82.5","s82.6","s82.7","s82.8","s82.9","s92","s92.0","s92.1","s92.2","s92.3","s92.4","s92.5","s92.7","s92.9","t02.3","t02.5","t12","t93.1","t93.2","t02.8","t02.9","t14.2"),collapse = "|")

frac <- filter(rest, str_detect(allinj, frac_inj))
frac$inj_type <- "Fracture"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(frac)))

disl_inj <- str_c(c("s03.0","s03.1","s03.2","s03.3","s13.0","s13.1","s13.2","s13.3","s23.0","s23.1","s33.0","s33.1","s33.2","s23.2","s33.3","s33.4","s43.0","s43.1","s43.2","s43.3","s53.0","s53.1","s63.0","s63.1","s63.2","s73.0","s83.0","s83.1","s93","s93.0","s93.1","s93.3"),collapse = "|")

disl <- filter(rest, str_detect(allinj, disl_inj))
disl$inj_type <- "Dislocation"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(disl)))

multiple_inj <- str_c(c("s09.7","s19.7","s27.7","s29.7","t03.1","t09.2","s49.7","s59.7","s69.7","t03.2","t11.2","t92.3","t92.6","s79.7","s89.7","s99.7","t03.3","t13.2","t93.3","t93.6","t03.8","t03.9","t91.0","t14.3","t14.7"),collapse = "|")

multiple <- filter(rest, str_detect(allinj, multiple_inj))
multiple$inj_type <- "Multiple Injuries"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(multiple)))

unspe_inj <- str_c(c("S099","T909","S059","S199","S269","S299","S399","T099","S499","S599","S699","T119","T929","S799","S837","S899","S999","T139","T939","T07","T919","T940","T148","T149","T941","T981"),collapse = "|")

unspe <- filter(rest, str_detect(allinj, unspe_inj))
unspe$inj_type <- "Unspecified Injury"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(unspe)))

open_inj <- str_c(c("s01","s01.0","s01.1","s01.2","s01.3","s01.4","s01.5","s01.7","s01.8","s01.9","t90.1","s05.2","s05.3","s05.4","s05.5","s05.6","s05.7","s08.0","s09.2","s11","s11.0","s11.1","s11.2","s11.7","s11.8","s11.9","s21","s21.0","s21.1","s21.2","s21.7","s21.8","s21.9","s31.1","s31.8","s31.0","s31.2","s31.3","s31.4","s31.5","s31.7","t09.1","s41","s41.0","s41.1","s41.7","s41.8","s51","s51.0","s51.7","s51.8","s51.9","s61","s61.0","s61.1","s617","s61.8","s61.9","t01.2","t11.1","t92.0","s71.0","s71.1","s71.2","s71.3","s71.4","s71.5","s71.6","s71.7","s71.8","s81","s81.0","s81.7","s81.8","s81.9","s91","s91.0","s91.1","s91.2","s91.3","s91.7","t01.3","t13.1","t93.0","t01.9","t14.1"),collapse = "|")

open <- filter(rest, str_detect(allinj, open_inj))
open$inj_type <- "Open wound"
rest <- suppressWarnings(suppressMessages(rest %>% anti_join(open)))

supf_inj <- str_c(c("s00","s00.0","s00.1","s00.2","s00.3","s00.4","s00.5","s00.7","s00.8","s00.9","s05.0","s05.1","t90.0","s10","s10.0","s10.1","s10.7","s10.8","s10.9","s20","s20.0","s20.1","s20.2","s20.3","s20.4","s20.7","s20.8","s30.1","s30.0","s30.2","s30.7","s30.8","s30.9","t09.0","s40","s40.0","s40.7","s40.8","s40.9","s50","s50.0","s50.1","s50.7","s50.8","s50.9","s60","s60.0","s60.1","s60.2","s60.7","s60.8","s60.9","t00.2","t11.0","s70","s70.0","s70.1","s70.2","s70.3","s70.4","s70.5","s70.6","s70.7","s70.8","s70.9","s80","s80.0","s80.1","s80.7","s80.8","s80.9","s90","s90.0","s90.1","s90.2","s90.3","s90.7","s90.8","s90.9","t00.3","t13.0","t00.8","t00.9","t14.0","t15.0"),collapse = "|")

supf <- filter(rest, str_detect(allinj, supf_inj))
supf$inj_type <- "Superficial Injury"
no_def_inj <- suppressWarnings(suppressMessages(rest %>% anti_join(supf)))
no_def_inj$inj_type <- "No defined Injury"
fall <- suppressWarnings(suppressMessages(rbind(no_def_inj,supf,open,unspe,multiple,disl,frac,amputation,bv,internal,crush)))

# Nature and location of Injury
# Crush injury

crush.lw.ex <- str_c(c("s77.1","s77.2","s87","s87.0","s87.8","s97","s97.0","s97.1","s97.8","t04.3"), collapse = "|")
crush_lw.ex <- filter(fall, str_detect(allinj, crush.lw.ex))

# Internal Injury

internal.tbi <- str_c(c("s06","s06.0","s06.1","s06.2","s06.3","s06.4","s06.5","s06.6","s06.7","s06.8","s06.9","t90.5"),collapse = "|")
internal_tbi <- filter(fall,str_detect(allinj, internal.tbi))

internal.sc <- str_c(c("s14.0","s14.1","s24.0","s24.1","s34.0","s34.1","s34.3","t09.3","t91.3"),collapse = "|")
internal_sc <- filter(fall, str_detect(allinj, internal.sc))

internal.vc <- str_c("s14.2",collapse = "|")
internal_vc <- filter(fall, str_detect(allinj, internal.vc))

internal.thorax <- str_c(c("s26.0","s27.0","s27.1","s27.2","s27.3","s27.4","s27.5","s27.6","s27.8","s27.9","t91.4"), collapse = "|")
internal_thorax <- filter(fall, str_detect(allinj, internal.thorax))

internal.abd <- str_c(c("s36","s36.0","s36.1","s36.2","s36.3","s36.4","s36.5","s36.6","s36.7","s36.8","s36.9"), collapse = "|")
internal_abd <- filter(fall, str_detect(allinj, internal.abd))

internal.plb <- str_c(c("s37","s37.0","s37.1","s37.2","s37.3","s37.4","s37.5","s37.6","s37.7","s37.8","s37.9"), collapse = "|")
internal_plb <- filter(fall, str_detect(allinj, internal.plb))

internal.abd.plb <- str_c(c("s39.6","s39.7","t06.5","t91.5"), collapse = "|")
internal_abd_plb <- filter(fall, str_detect(allinj, internal.abd.plb))

# Blood Vessel Injury

bv.other.head <- str_c("s09.0", collapse = "|")
bv_other_head <- filter(fall, str_detect(allinj, bv.other.head))

bv.neck <- str_c(c("s15.0","s51.2","s15.3","s15.4","s15.5","s15.6","s15.7","s15.8","s15.9"), collapse = "|")
bv_neck <- filter(fall, str_detect(allinj, bv.neck))

bv.thorax <- str_c(c("s25","s25.0","s25.1","s25.2","s25.3","s25.4","s25.5","s25.7","s25.8","s25.9"), collapse = "|")
bv_thorax <- filter(fall, str_detect(allinj, bv.thorax))

bv.abd <- str_c(c("s35.0","s35.1","s35.2","s35.3","s35.4"), collapse = "|")
bv_abd <- filter(fall, str_detect(allinj, bv.abd))

bv.pbl <- str_c("s35.5", collapse = "|")
bv_pbl <- filter(fall, str_detect(allinj, bv.pbl))

bv.abd.pbl <- str_c(c("s35.7","s35.8","s35.9"), collapse = "|")
bv_abd_pbl <- filter(fall, str_detect(allinj, bv.abd.pbl))

bv.up.ex <- str_c(c("s45","s45.0","s45.1","s45.2","s45.3","s45.7","s45.8","s45.9","s55","s55.0","s55.1","s55.2","s55.7","s55.8","s55.9","s65","s65.0","s65.1","s65.2","s65.3","s65.4","s65.5","s65.7","s65.8","s65.9","t11.4"), collapse = "|")
bv_up_ex <- filter(fall, str_detect(allinj, bv.up.ex))

bv.lw.ex <- str_c(c("s75","s75.0","s75.1","s75.2","s75.7","s75.8","s75.9","s85","s85.0","s85.1","s85.2","s85.3","s85.4","s85.5","s85.7","s85.8","s85.9","s95","s95.0","s95.1","s95.2","s95.7","s95.8","s95.9","t13.4"), collapse = "|")
bv_lw_ex <- filter(fall, str_detect(allinj, bv.lw.ex))

bv.multiple <- str_c("t06.3", collapse = "|")
bv_multiple <- filter(fall, str_detect(allinj, bv.multiple))

bv.unspe <- str_c("t14.5", collapse = "|")
bv_unspe <- filter(fall, str_detect(allinj, bv.unspe))

#Amputation

amp.up.ex <- str_c(c("s48","s48.0","s48.1","s48.9","s58","s58.0","s58.1","s58,9","s68","s68.0","s68.1","s68.2","s68.3","s68.4","s68.8","s68.9","t05.0","t05.2","t11.6"),collapse = "|")
amp_up_ex <- filter(fall, str_detect(allinj, amp.up.ex))

amp.other.lw.ex <- str_c(c("s78.1","s78.2","s78.3","s78.4","s78.5","s78.6","s78.7","s78.8","s78.9","s88","s88.0","s88.1","s88.9","s98","s98.0","s98.1","s98.2","s98.3","s98.4","s78.0","t05.3","t05.5","t13.6"),collapse = "|")
amp_other_lw_ex <- filter(fall, str_detect(allinj, amp.other.lw.ex))

# Fracture

frac.tbi <- str_c(c("s02","s02.0","s02.1","s02.3","s02.7","s02.9","t90.2"), collapse = "|")
frac_tbi <- filter(fall, str_detect(allinj, frac.tbi))
frac_tbi$fracture <- "TBI"

frac.other.head <- str_c(c("s02.2","s02.4","s02.5","s02.6"), collapse = "|")
frac_other_head <- filter(fall, str_detect(allinj, frac.other.head))
frac_other_head$fracture <- "Other head"

frac.neck <- str_c(c("s12","s12.8","s12.9"),collapse = "|")
frac_neck <- filter(fall, str_detect(allinj, frac.neck))
frac_neck$fracture <- "Neck"

frac.vertebral.col <- str_c(c("s12.0","s12.1","s12.2","s12.3","s12.4","s12.5","s12.6","s12.7","s22","s22.0","s22.1","s32","s32.0","s32.1","s32.2","t08","t91.1"),collapse = "|")
frac_vertebral_col <- filter(fall, str_detect(allinj, frac.vertebral.col))
frac_vertebral_col$fracture <- "Vertebral Column"

frac.thorax <- str_c(c("s22.2","s22.3","s22.4","s22.5","s22.6","s22.7","s22.8","s22.9"),collapse = "|")
frac_thorax <- filter(fall, str_detect(allinj, frac.thorax))
frac_thorax$fracture <- "Thorax"

frac.plb <- str_c(c("s32.3","s32.4","s32.5","s32.6","s32.7","s32.8","t02.1"),collapse = "|")
frac_plb <- filter(fall, str_detect(allinj, frac.plb))
frac_plb$fracture <- "Pelvis and Lower back"

frac.up.ex <- str_c(c("s42","s42.0","s42.1","s42.2","s42.3","s42.4","s42.7","s42.8","s42.9","s52","s52.0","s52.1","s52.2","s52.3","s52.4","s52.5","s52.6","s52.7","s52.8","s52.9","s62","s62.0","s62.1","s62.2","s62.3","s62.4","s62.5","s62.6","s62.7","s62.8","t02.2","t02.4","t10","t92.1","t92.2"), collapse = "|")
frac_up_ex <- filter(fall,str_detect(allinj, frac.up.ex))
frac_up_ex$fracture <- "Upper Extremeties"

frac.hip <- str_c(c("s72","s72.0","s72.1","s72.2"),collapse = "|")
frac_hip <- filter(fall, str_detect(allinj,frac.hip))
frac_hip$fracture <- "Hip"

frac.other.lw.ex <-str_c(c("s72.3","s72.4","s72.5","s72.6","s72.7","s72.8","s72.9","s82","s82.0","s82.1","s82.2","s82.3","s82.4","s82.5","s82.6","s82.7","s82.8","s82.9","s92","s92.0","s92.1","s92.2","s92.3","s92.4","s92.5","s92.7","s92.9","t02.3","t02.5","t12","t93.1","t93.2"),collapse = "|")
frac_other_lw_ex <- filter(fall,str_detect(allinj, frac.other.lw.ex))
frac_other_lw_ex$fracture <- "Lower extremeties"

frac.multiple <- str_c(c("t02.8","t02.9"),collapse = "|")
frac_multiple <- filter(fall,str_detect(allinj,frac.multiple))
frac_multiple$fracture <- "Multiple"

frac.unspecified <- str_c("t14.2",collapse = "|")
frac_unspecified <- filter(fall,str_detect(allinj, frac.unspecified))
frac_unspecified$fracture <- "Unspecified"

f <- rbind(frac_unspecified,frac_multiple,frac_other_lw_ex,frac_hip,frac_up_ex,frac_plb,frac_thorax,frac_vertebral_col,frac_neck,frac_other_head,frac_tbi)

#table(f$fracture,f$tagegrp,f$sex)

# Dislocation

disl.other.head <- str_c(c("s03.0","s03.1","s03.2","s03.3"),collapse = "|")
disl_other_head <- filter(fall, str_detect(allinj, disl.other.head))

disl.neck <- str_c(c("s13.2","s13.3"),collapse = "|")
disl_neck <- filter(fall, str_detect(allinj, disl.neck))

disl.vc <- str_c(c("s13.0","s13.1","s23.0","s23.1","s33.0","s33.1","s33.2"),collapse = "|")
disl_vc <- filter(fall, str_detect(allinj, disl.vc))

disl.thorax <- str_c("s23.2",collapse = "|")
disl_thorax <- filter(fall, str_detect(allinj, disl.thorax))

disl.plb <- str_c(c("s33.3","s33.4"),collapse = "|")
disl_plb <- filter(fall, str_detect(allinj, disl.plb))

disl.up.ex <- str_c(c("s43.0","s43.1","s43.2","s43.3","s53.0","s53.1","s63.0","s63.1","s63.2"),collapse = "|")
disl_up_ex <- filter(fall, str_detect(allinj, disl.up.ex))

disl.hip <- str_c("s73.0",collapse = "|")
disl_hip <- filter(fall,str_detect(allinj,disl.hip))

disl.multiple <- str_c(c("s83.0","s83.1","s93","s93.0","s93.1","s93.3","t14.3"),collapse = "|")
disl_multiple <- filter(fall, str_detect(allinj, disl.multiple))

# Multiple injury

multiple.tbi <- str_c("s09.7", collapse = "|")
multiple_tbi <- filter(fall, str_detect(allinj, multiple.tbi))

multiple.neck <- str_c("s19.7", collapse = "|")
multiple_neck <- filter(fall, str_detect(allinj, multiple.neck))

multiple.thorax <- str_c(c("s27.7","s29.7"), collapse = "|")
multiple_thorax <- filter(fall, str_detect(allinj, multiple.thorax))

multiple.lw.ex <- str_c("t03.1", collapse = "|")
multiple_lw_ex <- filter(fall, str_detect(allinj, multiple.lw.ex))

multiple.trunk <- str_c("t09.2", collapse = "|")
multiple_trunk <- filter(fall, str_detect(allinj, multiple.trunk))

multiple.up.ex <- str_c(c("s49.7","s59.7","s69.7","t03.2","t11.2","t92.3","t92.6"), collapse = "|")
multiple_up_ex <- filter(fall, str_detect(allinj, multiple.up.ex))

multiple.lw.ex <- str_c(c("s79.7","s89.7","s99.7","t03.3","t13.2","t93.3","t93.6"), collapse = "|")
multiple_lw_ex <- filter(fall, str_detect(allinj, multiple.lw.ex))

multiple.unspe <- str_c(c("t14.3","t14.7"),collapse = "|")
multiple_unspe <- filter(fall, str_detect(allinj, multiple.unspe))

# Unspecified injury

unspe.tbi <- str_c(c("s09.9","t90.9"), collapse = "|")
unspe_tbi <- filter(fall, str_detect(allinj, unspe.tbi))

unspe.other.head <- str_c("s05.9", collapse = "|")
unspe_other_head <- filter(fall, str_detect(allinj, unspe.other.head))

unspe.other.head <- str_c("s19.9", collapse = "|")
unspe_other_head <- filter(fall, str_detect(allinj, unspe.other.head))

unspe.thorax <- str_c(c("s26.9","s29.9"), collapse = "|")
unspe_thorax <- filter(fall, str_detect(allinj, unspe.thorax))

unspe.abd.pbl <- str_c("s39.9", collapse = "|")
unspe_abd_pbl <- filter(fall, str_detect(allinj, unspe.abd.pbl))

unspe.trunk <- str_c("t09.9", collapse = "|")
unspe_trunk <- filter(fall, str_detect(allinj, unspe.trunk))

unspe.up.ex <- str_c(c("s49.9","s59.9","s69.9","t11.9","t92.9"), collapse = "|")
unspe_up_ex <- filter(fall, str_detect(allinj, unspe.up.ex))

unspe.lw.ex <- str_c(c("s79.9","s83.7","s89.9","s99.9","t13.9","t93.9"), collapse = "|")
unspe_lw_ex <- filter(fall, str_detect(allinj, unspe.lw.ex))

unspe.multiple <- str_c(c("t07","t91.9","t94.0"), collapse = "|")
unspe_multiple <- filter(fall, str_detect(allinj, unspe.multiple))

unspe.unspe <- str_c(c("t14.8","t14.9","t94.1","t98.1"),collapse = "|")
unspe_unspe <- filter(fall, str_detect(allinj, unspe.unspe))

# Open Wound

ow.tbi <- str_c(c("s01","s01.0","s01.1","s01.2","s01.3","s01.4","s01.5","s01.7","s01.8","s01.9","t90.1"),collapse = "|")
ow_tbi <- filter(fall, str_detect(allinj, ow.tbi))

ow.other.head <- str_c(c("s05.2","s05.3","s05.4","s05.5","s05.6","s05.7","s08.0","s09.2"),collapse = "|")
ow_other_head <- filter(fall, str_detect(allinj, ow.other.head))

ow.neck <- str_c(c("s11","s11.0","s11.1","s11.2","s11.7","s11.8","s11.9"), collapse = "|")
ow_neck <- filter(fall, str_detect(allinj, ow.neck))

ow.thorax <- str_c(c("s21","s21.0","s21.1","s21.2","s21.7","s21.8","s21.9"), collapse = "|")
ow_thorax <- filter(fall, str_detect(allinj,ow.thorax))

ow.abd <- str_c(c("s31.1","s31.8"), collapse = "|")
ow_abd <- filter(fall, str_detect(allinj,ow.abd))

ow.pbl <- str_c(c("s31.0","s31.2","s31.3","s31.4","s31.5"), collapse = "|")
ow_pbl <- filter(fall, str_detect(allinj, ow.pbl))

ow.abd.pbl <- str_c("s31.7", collapse = "|")
ow_abd_pbl <- filter(fall, str_detect(allinj, ow.abd.pbl))

ow.other.trunk <- str_c("t09.1", collapse = "|")
ow_other_trunk <- filter(fall, str_detect(allinj, ow.other.trunk))

ow.up.ex <- str_c(c("s41","s41.0","s41.1","s41.7","s41.8","s51","s51.0","s51.7","s51.8","s51.9","s61","s61.0","s61.1","s617","s61.8","s61.9","t01.2","t11.1","t92.0"), collapse = "|")
ow_up_ex <- filter(fall, str_detect(allinj, ow.up.ex))

ow.hip <- str_c("s71.0", collapse = "|")
ow_hip <- filter(fall, str_detect(allinj, ow.hip))

ow.other.lw.ex <- str_c(c("s71.1","s71.2","s71.3","s71.4","s71.5","s71.6","s71.7","s71.8","s81","s81.0","s81.7","s81.8","s81.9","s91","s91.0","s91.1","s91.2","s91.3","s91.7","t01.3","t13.1","t93.0"),collapse = "|")
ow_other_lw_ex <- filter(fall, str_detect(allinj, ow.other.lw.ex))

ow.unspe <- str_c("t14.1", collapse = "|")
ow_unspe <- filter(fall, str_detect(allinj, ow.unspe))

# Superficial Injury

sup.other.head <- str_c(c("s00","s00.0","s00.1","s00.2","s00.3","s00.4","s00.5","s00.7","s00.8","s00.9","s05.0","s05.1","t90.0"), collapse = "|")
sup_other_head <- filter(fall, str_detect(allinj, sup.other.head))

sup.neck <- str_c(c("s10","s10.0","s10.1","s10.7","s10.8","s10.9"), collapse = "|")
sup_neck <- filter(fall, str_detect(allinj, sup.neck))

sup.thorax <- str_c(c("s20","s20.0","s20.1","s20.2","s20.3","s20.4","s20.7","s20.8"), collapse = "|")
sup_thorax <- filter(fall, str_detect(allinj, sup.thorax))

sup.abd <- str_c("s30.1", collapse = "|")
sup_abd <- filter(fall, str_detect(allinj, sup.abd))

sup.pbl <- str_c(c("s30.0","s30.2"), collapse = "|")
sup_pbl <- filter(fall, str_detect(allinj, sup.pbl))

sup.abd.pbl <- str_c(c("s30.7","s30.8","s30.9"), collapse = "|")
sup_abd_pbl <- filter(fall, str_detect(allinj, sup.abd.pbl))

sup.trunk <- str_c("t09.0", collapse = "|")
sup_trunk <- filter(fall, str_detect(allinj, sup.trunk))

sup.up.ex <- str_c(c("s40","s40.0","s40.7","s40.8","s40.9","s50","s50.0","s50.1","s50.7","s50.8","s50.9","s60","s60.0","s60.1","s60.2","s60.7","s60.8","s60.9","t00.2","t11.0"), collapse = "|")
sup_up_ex <- filter(fall, str_detect(allinj, sup.up.ex))

sup.hip <- str_c(c("s70","s70.0"), collapse = "|")
sup_hip <- filter(fall, str_detect(allinj, sup.hip))

sup.lw.ex <- str_c(c("s70","s70.0","s70.1","s70.2","s70.3","s70.4","s70.5","s70.6","s70.7","s70.8","s70.9","s80","s80.0","s80.1","s80.7","s80.8","s80.9","s90","s90.0","s90.1","s90.2","s90.3","s90.7","s90.8","s90.9","t00.3","t13.0"), collapse = "|")
sup_lw_ex <- filter(fall, str_detect(allinj, sup.lw.ex))

sup.multiple <- str_c(c("t00.8","t00.9"), collapse = "|")
sup_multiple <- filter(fall, str_detect(allinj, sup.multiple))

sup.unspe <- str_c(c("t14.0","t15.0"),collapse = "|")
supf_unspe <- filter(fall, str_detect(allinj, sup.unspe))

# Other specified injury

spec.tbi <- str_c(c("s04.0", "s09.8", "t90.4", "t904.8"), collapse = "|")
spec_tbi <- filter(fall, str_detect(allinj, spec.tbi))

spec.other.head <- str_c(c("s03.4", "s03.5","s04.1","s04.2","s04.3","s04.4","s04.5","s04.6","s04.7","s04.8","s04.9", "s05.8","s09.1","t90.3"), collapse = "|")
spec_other_head <- filter(fall, str_detect(allinj, spec.other.head))

spec.neck <- str_c(c("s13.5","s13.6","s14.3","s14.4","s14.5","s14.6","s16","s19.8"), collapse = "|")
spec_neck <- filter(fall, str_detect(allinj,spec.neck))

spec.thorax <- str_c(c("s23.4","s23.5","s24.3","s24.4","s24.5","s24.6","s26.8","s29.0","s29.8"), collapse = "|")
spec_thorax <- filter(fall, str_detect(allinj,spec.thorax))

spec.abd.plb <- str_c(c("s34.6","s34.8","s39.0","s39.8"), collapse = "|")
spec_abd_plb <- filter(fall, str_detect(allinj,spec.abd.plb))

spec.trunk <- str_c(c("t09.5","t09.8"), collapse = "|")
spec_trunk <- filter(fall, str_detect(allinj,spec.trunk))

spec.up.ex <- str_c(c("s43.4","s43.5","s43.6","s43.7","s44","s44.0","s44.1","s44.2","s44.3","s44.4","s44.5","s44.7","s44.8","s44.9","s46","s46.0","s46.1","s46.2","s46.3","s46.7","s46.8","s46.9","s49.8","s53.2","s53.3","s53.4","s54","s54.0","s54.1","s54.2","s54.3","s54.7","s54.8","s54.9","s56","s56.0","s56.1","s56.2","s56.3","s56.4","s56.5","s56.7","s56.8","s59.8","s63.3","s63.4","s63.5","s63.6","s63.7","s64","s64.0","s64.1","s64.2","s64.3","s64.4","s64.7","s64.8","s64.9","s66","s66.0","s66.1","s66.2","s66.3","s66.4","s66.5","s66.6","s66.7","s66.8","s66.9","s69.8","t11.3","t11.5","t11.8","t92.4","t92.5","t92.8"), collapse = "|")
spec_up_ex <- filter(fall, str_detect(allinj,spec.up.ex))

spec.hip <- str_c(c("s74","s74.0","s74.1","s74.2","s74.7","s74.8","s74.9","s76.0","s76","s76.0","s76.1","s76.2","s76.3","s76.4","s76.7","s79.8","s83.2","s83.3","s83.4","s83.5","s83.6","s84","s84.0","s84.1","s84.2","s84.7","s84.8","s84.9","s86","s86.0","s86.1","s86.2","s86.3","s86.7","s86.8","s86.9","s89.8","s93.2","s93.4","s93.5","s93.6","s94","s94.0","s94.1","s94.2","s94.3","s94.7","s94.8","s94.9","s96","s96.0","s96.1","s96.2","s96.7","s96.8","s96.9","s99.8","t13.3","t13.5","t13.8","t93.4","t93.5"), collapse = "|")
spec_hip <- filter(fall, str_detect(allinj,spec.hip))

spec.lw.ex <- str_c(c("t06.2","t06.4","t91.8"),collapse = "|")
spec_lw_ex <- filter(fall, str_detect(allinj, spec.lw.ex))

spec.multiple <- str_c(c("t79","t79.0","t79.1","t79.2","t79.3","t79.4","t79.5","t79.6","t79.7","t79.8","t79.9","t98.2"),collapse = "|")
spec_multiple <- filter(fall, str_detect(allinj, spec.multiple))

spec.unspe <- str_c(c("t14.4","t14.6"),collapse = "|")
spec_unspe <- filter(fall, str_detect(allinj, spec.unspe))

## Creating Table for TBI patients demography using table one
fall$died<-factor(fall$died, levels = c("Yes","No"), labels = c("Died", "Survived"))
fall$surgery <- factor(if_else(fall$tos == 0, "Conservative","Operative"))

var_label(fall) <- list(sex="Sex",
                        age="Age",
                        agegrp="Age Group",
                        ti = "Type of injury",
                        mot="Mode of transport",
                        tran = "Transferred",
                        sbp_1="Systolic blood pressure",
                        hr_1="Heart rate",
                        spo2_1="Saturation",
                        rr_1="Respiratory rate",
                        gcsgrp="Glasgow comma scale",
                        surgery="Surgery",
                        died = "Mortality",
                        isspv = "Injury Severity Score (ISS)",
                        inj_type="Injury type",
                        died = "Mortality")

myvars <- c("age","sex","agegrp","ti","mot","sbp_1","hr_1","spo2_1","rr_1","gcsgrp","surgery","isspv","inj_type","died")
catvars <- c("sex","agegrp","ti","mot","gcsgrp","surgery","isspv","inj_type","died")

Table1 <- CreateTableOne(vars = myvars, strata = "tran", data=fall, factorVars = catvars)
knitr::kable(print(Table1,
                   caption = "Table 1. Demographic, Physiological parameters", showAllLevels = TRUE, printToggle = FALSE, varLabels = TRUE))

```

